CREATE TABLE urls
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_url TEXT                                    NOT NULL,
    short_code   VARCHAR(10)                             NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    click_count  BIGINT,
    CONSTRAINT pk_urls PRIMARY KEY (id)
);

ALTER TABLE urls
    ADD CONSTRAINT uc_urls_shortcode UNIQUE (short_code);

CREATE INDEX idx_short_code ON urls (short_code);