CREATE TABLE profile
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                VARCHAR(255)                            NOT NULL,
    first_name          VARCHAR(255),
    last_name           VARCHAR(255),
    profile_picture_url VARCHAR(255),
    user_id             BIGINT,
    CONSTRAINT pk_profile PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid     VARCHAR(255)                            NOT NULL,
    username VARCHAR(50)                             NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE urls
    ADD user_id BIGINT;

ALTER TABLE urls
    ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE profile
    ADD CONSTRAINT uc_profile_user UNIQUE (user_id);

ALTER TABLE profile
    ADD CONSTRAINT uc_profile_uuid UNIQUE (uuid);

-- ALTER TABLE users
--     ADD CONSTRAINT uc_user_username UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT uc_user_uuid UNIQUE (uuid);

ALTER TABLE profile
    ADD CONSTRAINT FK_PROFILE_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE urls
    ADD CONSTRAINT FK_URLS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE profile
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE profile
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ADD email VARCHAR(100);

ALTER TABLE users
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ALTER COLUMN email SET NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

CREATE INDEX idx_short_code ON urls (short_code);